### ISSUE TITLE
Division by 0 error - when all but 1 in historical sales is 0 in Normalize method

### ISSUE THREAD

**Issue by nayan1247** [ourownstory/neural_prophet#122]
future_df = df_utils.normalize(future_df, self.data_params) 

Normalize method is giving a divide by zero error when all but 1 in the historical data is 0.  Trace below for the error.

`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/dummyuser/Documents/demand_forecast/demand_forecast/core_forecast.py", line 217, in predict
    pred = model.predict(model.make_future_dataframe(df=df_train[['ds', 'y']], future_periods=horizon))
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/neuralprophet/neural_prophet.py", line 835, in make_future_dataframe
    future_df = df_utils.normalize(future_df, self.data_params)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/neuralprophet/df_utils.py", line 123, in normalize
    df[new_name] = df[new_name].div(data_params[name].scale)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 580, in flex_wrapper
    return op(self, other)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 503, in wrapper
    result = arithmetic_op(lvalues, rvalues, op, str_rep)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 197, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op, str_rep)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 149, in na_arithmetic_op
    result = expressions.evaluate(op, str_rep, left, right)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b)
  File "/Users/dummyuser/opt/anaconda3/envs/demand_forecast/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
`

**Comment by ourownstory** [comment]
Thank you for contributing the bug report @nayan1247!

It should have been fixed in the linked PR. 
In your case, it should now use minmax normalization as your input is binary. 
I added a [unittests here](https://github.com/ourownstory/neural_prophet/blob/0c38c5df63e76a4ce35a836864c6b03ba947d9a9/tests/test_unit.py#L96). Does this replicate your situation?
Please let us know if the bug is fixed now (fix is merged to master now).
