### ISSUE TITLE
Getting RuntimeError: unknown Parameter type

### ISSUE THREAD

**Issue by aravindravva** [ourownstory/neural_prophet#1480]
**Prerequisites**

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Discussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solvable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**

We are running an forecast model in the production getting the error on runtime 

**Logs**

```
2023-11-21T09:06:16.245742430Z 21-11-2023:09:06:16,234 ERROR    [pod_usage_forecasting.py:136] unknown parameter type
2023-11-21T09:06:16.245826880Z Traceback (most recent call last):
2023-11-21T09:06:16.245836991Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
2023-11-21T09:06:16.245841631Z     return trainer_fn(*args, **kwargs)
2023-11-21T09:06:16.245847261Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
2023-11-21T09:06:16.245851421Z     self._run(model, ckpt_path=self.ckpt_path)
2023-11-21T09:06:16.245855301Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1097, in _run
2023-11-21T09:06:16.245859411Z     self._call_callback_hooks("on_fit_start")
2023-11-21T09:06:16.245863111Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1394, in _call_callback_hooks
2023-11-21T09:06:16.245867281Z     fn(self, self.lightning_module, *args, **kwargs)
2023-11-21T09:06:16.245870981Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/callbacks/lr_finder.py", line 122, in on_fit_start
2023-11-21T09:06:16.245874761Z     self.lr_find(trainer, pl_module)
2023-11-21T09:06:16.245878981Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/callbacks/lr_finder.py", line 107, in lr_find
2023-11-21T09:06:16.245883001Z     self.optimal_lr = lr_find(
2023-11-21T09:06:16.245886401Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/tuner/lr_finder.py", line 247, in lr_find
2023-11-21T09:06:16.245889821Z     _try_loop_run(trainer, params)
2023-11-21T09:06:16.245893421Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/tuner/lr_finder.py", line 481, in _try_loop_run
2023-11-21T09:06:16.245906471Z     loop.run()
2023-11-21T09:06:16.245910401Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-11-21T09:06:16.245913911Z     self.advance(*args, **kwargs)
2023-11-21T09:06:16.245917491Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
2023-11-21T09:06:16.245921211Z     self._outputs = self.epoch_loop.run(self._data_fetcher)
2023-11-21T09:06:16.245924791Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-11-21T09:06:16.245928571Z     self.advance(*args, **kwargs)
2023-11-21T09:06:16.245932231Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
2023-11-21T09:06:16.245935851Z     batch_output = self.batch_loop.run(kwargs)
2023-11-21T09:06:16.245939531Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-11-21T09:06:16.245943031Z     self.advance(*args, **kwargs)
2023-11-21T09:06:16.245946591Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 90, in advance
2023-11-21T09:06:16.245950211Z     outputs = self.manual_loop.run(kwargs)
2023-11-21T09:06:16.245953651Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-11-21T09:06:16.245957391Z     self.advance(*args, **kwargs)
2023-11-21T09:06:16.245961061Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 110, in advance
2023-11-21T09:06:16.245964761Z     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
2023-11-21T09:06:16.245968221Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
2023-11-21T09:06:16.245971961Z     output = fn(*args, **kwargs)
2023-11-21T09:06:16.245975501Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
2023-11-21T09:06:16.245979061Z     return self.model.training_step(*args, **kwargs)
2023-11-21T09:06:16.245982971Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/time_net.py", line 791, in training_step
2023-11-21T09:06:16.245986531Z     self.log_dict(self.metrics_train(predicted_denorm, target_denorm), **self.log_args)
2023-11-21T09:06:16.245990111Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 583, in log_dict
2023-11-21T09:06:16.245994001Z     self.log(
2023-11-21T09:06:16.245998391Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 502, in log
2023-11-21T09:06:16.246002361Z     results.log(
2023-11-21T09:06:16.246006071Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 498, in log
2023-11-21T09:06:16.246010421Z     self.update_metrics(key, value, batch_size)
2023-11-21T09:06:16.246013731Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 521, in update_metrics
2023-11-21T09:06:16.246017171Z     apply_to_collections(self[key], value, _ResultMetric, fn)
2023-11-21T09:06:16.246020511Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 219, in apply_to_collections
2023-11-21T09:06:16.246023961Z     return function(data1, data2, *args, **kwargs)
2023-11-21T09:06:16.246027551Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 518, in fn
2023-11-21T09:06:16.246030671Z     result_metric.forward(v.to(self.device), batch_size)
2023-11-21T09:06:16.246044781Z RuntimeError: unknown parameter type
2023-11-21T09:06:16.246048641Z 
2023-11-21T09:06:16.246052892Z During handling of the above exception, another exception occurred:
2023-11-21T09:06:16.246055932Z 
2023-11-21T09:06:16.246059202Z Traceback (most recent call last):
2023-11-21T09:06:16.246062332Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 106, in get_forecasting
2023-11-21T09:06:16.246065532Z     forecasting = self.compute_forecasting(param)
2023-11-21T09:06:16.246068792Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 71, in compute_forecasting
2023-11-21T09:06:16.246072992Z     model.fit(data)
2023-11-21T09:06:16.246077302Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 946, in fit
2023-11-21T09:06:16.246080532Z     metrics_df = self._train(
2023-11-21T09:06:16.246083602Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 2632, in _train
2023-11-21T09:06:16.246087042Z     lr_finder = self.trainer.tuner.lr_find(
2023-11-21T09:06:16.246091172Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/tuner/tuning.py", line 267, in lr_find
2023-11-21T09:06:16.246094302Z     self.trainer.fit(model, train_dataloaders, val_dataloaders, datamodule)
2023-11-21T09:06:16.246097512Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
2023-11-21T09:06:16.246100862Z     call._call_and_handle_interrupt(
2023-11-21T09:06:16.246104573Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 63, in _call_and_handle_interrupt
2023-11-21T09:06:16.246108053Z     trainer._teardown()
2023-11-21T09:06:16.246111253Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1175, in _teardown
2023-11-21T09:06:16.246114623Z     self.strategy.teardown()
2023-11-21T09:06:16.246118243Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 492, in teardown
2023-11-21T09:06:16.246121503Z     _optimizers_to_device(self.optimizers, torch.device("cpu"))
2023-11-21T09:06:16.246125053Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/optimizer.py", line 28, in _optimizers_to_device
2023-11-21T09:06:16.246128493Z     _optimizer_to_device(opt, device)
2023-11-21T09:06:16.246131993Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/optimizer.py", line 34, in _optimizer_to_device
2023-11-21T09:06:16.246135713Z     optimizer.state[p] = apply_to_collection(v, Tensor, move_data_to_device, device)
2023-11-21T09:06:16.246139203Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 70, in apply_to_collection
2023-11-21T09:06:16.246142723Z     return {k: function(v, *args, **kwargs) for k, v in data.items()}
2023-11-21T09:06:16.246146253Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 70, in <dictcomp>
2023-11-21T09:06:16.246149783Z     return {k: function(v, *args, **kwargs) for k, v in data.items()}
2023-11-21T09:06:16.246153223Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/apply_func.py", line 101, in move_data_to_device
2023-11-21T09:06:16.246156763Z     return apply_to_collection(batch, dtype=_TransferableDataType, function=batch_to)
2023-11-21T09:06:16.246160413Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 64, in apply_to_collection
2023-11-21T09:06:16.246164183Z     return function(data, *args, **kwargs)
2023-11-21T09:06:16.246167773Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/apply_func.py", line 95, in batch_to
2023-11-21T09:06:16.246176113Z     data_output = data.to(device, **kwargs)
2023-11-21T09:06:16.246179743Z RuntimeError: unknown parameter type
```

If applicable, add screenshots and console printouts to help explain your problem.

**Environment (please complete the following information):**

 - Python environment 3.10
 - NeuralProphet version and install method [ 0.6.0, installed from PYPI with `pip install neuralprophet`]

**Comment by SimonWittner** [comment]
Hi, 
do you also face this issue when using a different dataset? How does your data look like?

**Comment by aravindravva** [comment]
it's coming intermittently 
what datatypes are supported , is the issue with data type ?

**Comment by aravindravva** [comment]
DataFrame(df)
     ds                        id          ...  memory_usage      isDeleted
0  2023-08-24  000000000000000000000000  ...  1.313153e+09       0.0
1  2023-08-25  000000000000000000000000  ...  1.523405e+09       0.0
2  2023-08-26  000000000000000000000000  ...  1.533841e+09       0.0
3  2023-08-27  000000000000000000000000  ...  1.438192e+09       0.0
4  2023-08-28  000000000000000000000000  ...  1.127608e+09       0.0
..        ...                       ...  ...           ...       ...
84 2023-11-16  000000000000000000000000  ...  2.043421e+09       0.0
85 2023-11-17  000000000000000000000000  ...  2.044424e+09       0.0
86 2023-11-18  000000000000000000000000  ...  2.043498e+09       0.0
87 2023-11-19  000000000000000000000000  ...  2.039394e+09       0.0
88 2023-11-20  000000000000000000000000  ...  2.044637e+09       0.0
 
[89 rows x 13 columns]

post that doing 
```
df1=self.df[['ds',"memory_usage"]]
df1.rename(columns={"memory_usage": 'y'}, inplace=True)
data=df1.copy()
model.fit(data) 
```

**Comment by SimonWittner** [comment]
Could you please verify if your issue is also occurring when using a different dataframe? 

In any case I would recommend you to check whether you could transform your ID to a string and to do the following before training: 

`data['y'] = pd.to_numeric(data['y'], errors='coerce')`
`data['y'] = data['y'].astype('float32')`
`data['ds'] = pd.to_datetime(data['ds'])`

**Comment by aravindravva** [comment]
@SimonWittner  Thanks for suggestion let me try that way

**Comment by aravindravva** [comment]
After trying the way you told got some error like this the old error disappeared now getting like
```
2023-11-23T10:26:29.686007824Z 23-11-2023:10:26:29,656 ERROR    [pod_usage_forecasting.py:139] can't convert np.ndarray of type numpy.datetime64. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
2023-11-23T10:26:29.686033655Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 109, in get_forecasting
2023-11-23T10:26:29.686037185Z     forecasting = self.compute_forecasting(param)
2023-11-23T10:26:29.686040075Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 74, in compute_forecasting
2023-11-23T10:26:29.686046385Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 946, in fit
2023-11-23T10:26:29.686052605Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 2572, in _train
2023-11-23T10:26:29.686058185Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 2501, in _init_train_loader
2023-11-23T10:26:29.686779681Z 23-11-2023:10:26:29,686 INFO     [pod_usage_forecasting.py:143] {}
2023-11-23T10:26:29.687450136Z 23-11-2023:10:26:29,686 INFO     [pod_usage_forecasting.py:159] ###########################################################################
2023-11-23T10:26:29.687731703Z 23-11-2023:10:26:29,687 INFO     [pod_usage_forecasting.py:160] {}
2023-11-23T10:26:29.687995029Z 23-11-2023:10:26:29,687 INFO     [pod_usage_forecasting.py:161] {}
2023-11-23T10:26:29.688267804Z 23-11-2023:10:26:29,687 INFO     [pod_usage_forecasting.py:162] [{'error_code': 'INSIGHTS_MODEL_103', 'exception': TypeError("can't convert np.ndarray of type numpy.datetime64. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool."), 'message': 'Error while creating forecast'}]
``

**Comment by aravindravva** [comment]
https://github.com/ourownstory/neural_prophet/issues/1317#issuecomment-1536463415

this issue partly fixed

**Comment by aravindravva** [comment]
> Could you please verify if your issue is also occurring when using a different dataframe?
> 
> In any case I would recommend you to check whether you could transform your ID to a string and to do the following before training:
> 
> `data['y'] = pd.to_numeric(data['y'], errors='coerce')` `data['y'] = data['y'].astype('float32')` `data['ds'] = pd.to_datetime(data['ds'])`

Issue not resolved still showing same

**Comment by aravindravva** [comment]
```
2023-12-03T13:15:30.265448179Z 03-12-2023:13:15:30,258 ERROR    [pod_usage_forecasting.py:140] unknown parameter type
2023-12-03T13:15:30.265507490Z Traceback (most recent call last):
2023-12-03T13:15:30.265522110Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
2023-12-03T13:15:30.265536140Z     self.fit_loop.run()
2023-12-03T13:15:30.265547730Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-12-03T13:15:30.265551420Z     self.advance(*args, **kwargs)
2023-12-03T13:15:30.265554691Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
2023-12-03T13:15:30.265557811Z     self._outputs = self.epoch_loop.run(self._data_fetcher)
2023-12-03T13:15:30.265560991Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-12-03T13:15:30.265565861Z     self.advance(*args, **kwargs)
2023-12-03T13:15:30.265569721Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
2023-12-03T13:15:30.265573001Z     batch_output = self.batch_loop.run(kwargs)
2023-12-03T13:15:30.265575981Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-12-03T13:15:30.265579001Z     self.advance(*args, **kwargs)
2023-12-03T13:15:30.265581861Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 90, in advance
2023-12-03T13:15:30.265584811Z     outputs = self.manual_loop.run(kwargs)
2023-12-03T13:15:30.265587741Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2023-12-03T13:15:30.265591211Z     self.advance(*args, **kwargs)
2023-12-03T13:15:30.265595271Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 110, in advance
2023-12-03T13:15:30.265599051Z     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
2023-12-03T13:15:30.265602891Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
2023-12-03T13:15:30.265607011Z     output = fn(*args, **kwargs)
2023-12-03T13:15:30.265610991Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
2023-12-03T13:15:30.265614702Z     return self.model.training_step(*args, **kwargs)
2023-12-03T13:15:30.265618462Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/time_net.py", line 802, in training_step
2023-12-03T13:15:30.265621492Z     self.log_dict(self.metrics_train(predicted_denorm, target_denorm), **self.log_args)
2023-12-03T13:15:30.265624852Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 583, in log_dict
2023-12-03T13:15:30.265634692Z     self.log(
2023-12-03T13:15:30.265637612Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 456, in log
2023-12-03T13:15:30.265640502Z     value = apply_to_collection(value, (Tensor, numbers.Number), self.__to_tensor, name)
2023-12-03T13:15:30.265646012Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 64, in apply_to_collection
2023-12-03T13:15:30.265649142Z     return function(data, *args, **kwargs)
2023-12-03T13:15:30.265652092Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 625, in __to_tensor
2023-12-03T13:15:30.265655072Z     value.clone().detach().to(self.device)
2023-12-03T13:15:30.265658042Z RuntimeError: unknown parameter type
2023-12-03T13:15:30.265660622Z 
2023-12-03T13:15:30.265663822Z During handling of the above exception, another exception occurred:
2023-12-03T13:15:30.265666412Z 
2023-12-03T13:15:30.265669162Z Traceback (most recent call last):
2023-12-03T13:15:30.265671983Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
2023-12-03T13:15:30.265675073Z     return trainer_fn(*args, **kwargs)
2023-12-03T13:15:30.265678593Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
2023-12-03T13:15:30.265682593Z     self._run(model, ckpt_path=self.ckpt_path)
2023-12-03T13:15:30.265687943Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
2023-12-03T13:15:30.265692043Z     results = self._run_stage()
2023-12-03T13:15:30.265695683Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
2023-12-03T13:15:30.265699383Z     self._run_train()
2023-12-03T13:15:30.265703013Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1213, in _run_train
2023-12-03T13:15:30.265706763Z     with torch.autograd.set_detect_anomaly(self._detect_anomaly):
2023-12-03T13:15:30.265710363Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/anomaly_mode.py", line 115, in __exit__
2023-12-03T13:15:30.265713603Z     torch.set_anomaly_enabled(self.prev, self.prev_check_nan)
2023-12-03T13:15:30.265716433Z RuntimeError: unknown parameter type
2023-12-03T13:15:30.265719023Z 
2023-12-03T13:15:30.265721803Z During handling of the above exception, another exception occurred:
2023-12-03T13:15:30.265765614Z 
2023-12-03T13:15:30.265769864Z Traceback (most recent call last):
2023-12-03T13:15:30.265772844Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 110, in get_forecasting
2023-12-03T13:15:30.265775734Z     forecasting = self.compute_forecasting(param)
2023-12-03T13:15:30.265778824Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 75, in compute_forecasting
2023-12-03T13:15:30.265808215Z     model.fit(data)
2023-12-03T13:15:30.265827885Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 946, in fit
2023-12-03T13:15:30.265832845Z     metrics_df = self._train(
2023-12-03T13:15:30.265836996Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 2642, in _train
2023-12-03T13:15:30.265840916Z     self.trainer.fit(
2023-12-03T13:15:30.265844646Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
2023-12-03T13:15:30.265848417Z     call._call_and_handle_interrupt(
2023-12-03T13:15:30.265851977Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 63, in _call_and_handle_interrupt
2023-12-03T13:15:30.265859897Z     trainer._teardown()
2023-12-03T13:15:30.265863657Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1175, in _teardown
2023-12-03T13:15:30.265867317Z     self.strategy.teardown()
2023-12-03T13:15:30.265871237Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 492, in teardown
2023-12-03T13:15:30.265874557Z     _optimizers_to_device(self.optimizers, torch.device("cpu"))
2023-12-03T13:15:30.265877417Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/optimizer.py", line 28, in _optimizers_to_device
2023-12-03T13:15:30.265880477Z     _optimizer_to_device(opt, device)
2023-12-03T13:15:30.265884027Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/optimizer.py", line 34, in _optimizer_to_device
2023-12-03T13:15:30.265887517Z     optimizer.state[p] = apply_to_collection(v, Tensor, move_data_to_device, device)
2023-12-03T13:15:30.265891157Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 70, in apply_to_collection
2023-12-03T13:15:30.265894697Z     return {k: function(v, *args, **kwargs) for k, v in data.items()}
2023-12-03T13:15:30.265898297Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 70, in <dictcomp>
2023-12-03T13:15:30.265902127Z     return {k: function(v, *args, **kwargs) for k, v in data.items()}
2023-12-03T13:15:30.265905798Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/apply_func.py", line 101, in move_data_to_device
2023-12-03T13:15:30.265909418Z     return apply_to_collection(batch, dtype=_TransferableDataType, function=batch_to)
2023-12-03T13:15:30.265913058Z   File "/usr/local/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 64, in apply_to_collection
2023-12-03T13:15:30.265916588Z     return function(data, *args, **kwargs)
2023-12-03T13:15:30.265919768Z   File "/usr/local/lib/python3.10/site-packages/lightning_fabric/utilities/apply_func.py", line 95, in batch_to
2023-12-03T13:15:30.265923268Z     data_output = data.to(device, **kwargs)

**Comment by SimonWittner** [comment]
Closed due to inactivity.
