### ISSUE TITLE
NameError: name 'register_plotly_resampler' is not defined

### ISSUE THREAD

**Issue by mixcheck** [ourownstory/neural_prophet#1496]
I install neuralprophet, plotly, plotly_resampler without version.

pip install neuralprophet, plotly, plotly_resampler

neuralprolet == 0.6.2
plotly == 5.15.0
plotly-resampler == 0.8.3.2

When I imiport neuralproplet, the error is below.

C:\Users\hanul.roh\AppData\Local\Programs\Python\Python38\lib\site-packages\plotly_resampler\aggregation\aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
  warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
Importing plotly failed. Interactive plots will not work.
Traceback (most recent call last):
  File "D:\SDCFCST\_forecast_market_data.py", line 2, in <module>
    from neuralprophet import NeuralProphet
  File "C:\Users\hanul.roh\AppData\Local\Programs\Python\Python38\lib\site-packages\neuralprophet\__init__.py", line 9, in <module>
    from .forecaster import NeuralProphet  # noqa: F401
  File "C:\Users\hanul.roh\AppData\Local\Programs\Python\Python38\lib\site-packages\neuralprophet\forecaster.py", line 30, in <module>
    from neuralprophet.plot_forecast_plotly import plot as plot_plotly
  File "C:\Users\hanul.roh\AppData\Local\Programs\Python\Python38\lib\site-packages\neuralprophet\plot_forecast_plotly.py", line 6, in <module>
    from neuralprophet.plot_model_parameters_plotly import get_dynamic_axis_range
  File "C:\Users\hanul.roh\AppData\Local\Programs\Python\Python38\lib\site-packages\neuralprophet\plot_model_parameters_plotly.py", line 38, in <module>
    register_plotly_resampler(mode="auto")
NameError: name 'register_plotly_resampler' is not defined

How can I fix it?
Thank you

**Comment by mixcheck** [comment]
I reinstall Ipython==8.12 then it works.
Thank you
