### ISSUE TITLE
Value Eerror with plain message

### ISSUE THREAD

**Issue by tulbureandreit** [ourownstory/neural_prophet#809]
I will try to be as short as possible.

I ran a Neural prophet forecasting job on multiple products

```
Task 'model_selection': Exception encountered during task execution!
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/builds/-/--prefect-workflows/workflows/worker_flow.py", line 108, in model_selection
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/python_translation/model_selection_master.py", line 483, in run_model_selection
    ) = cross_validate_neuralprophet(
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/python_translation/models/NeuralProphet.py", line 169, in cross_validate_neuralprophet
    train = NeuralProphet_model.fit(df=df_train, freq="W-MON")
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/forecaster.py", line 592, in fit
    metrics_df = self._train(df_dict, progress=progress)
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/forecaster.py", line 1806, in _train
    loader = self._init_train_loader(df_dict)
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/forecaster.py", line 1572, in _init_train_loader
    self.config_normalization.init_data_params(
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/configure.py", line 41, in init_data_params
    self.local_data_params, self.global_data_params = df_utils.init_data_params(
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/df_utils.py", line 260, in init_data_params
    global_data_params = data_params_definition(
  File "/root/.cache/pypoetry/virtualenvs/--py3.8/lib/python3.8/site-packages/neuralprophet/df_utils.py", line 176, in data_params_definition
    data_params[covar] = get_normalization_params(
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/df_utils.py", line 300, in get_normalization_params
    norm_type = auto_normalization_setting(array)
  File "/root/.cache/pypoetry/virtualenvs/--prefect-workflows-9TtSrW0h-py3.8/lib/python3.8/site-packages/neuralprophet/df_utils.py", line 290, in auto_normalization_setting
    raise ValueError
ValueError
```

**Describe the bug**
Ran a forecasting job ... and it raised a ValueError without any additional mentions.

**To Reproduce**

I really do not know. It was a Prefect job that I ran over 200 products. And I have no idea why it failed.

**Expected behavior**

I expected it to forecast without returning an error.

**What actually happens**

It crashes with a ValueError

**Screenshots**

Printouts are above.

**Environement (please complete the following information):**

 - Python environment: 3.8.10
 - NeuralProphet version: neuralprophet 0.3.2, installed from PYPI with `pip install neuralprophet`

**Additional context**

These are scheduled as a Prefect workflow. Hence I do not run things manually. Around 150 products ran without any issues. And this returned a ValueError.

**Comment by ourownstory** [comment]
Hi @tulbureandreit 
Thank you for sharing this issue.
Can you help us by giving us more context about the model and data that triggered this error?

**Comment by ourownstory** [comment]
It seems like it is this line that is throwing the error:
https://github.com/ourownstory/neural_prophet/blob/ea717ad31dec216ba670492f9b89fd075621dc3a/neuralprophet/df_utils.py#L320

@tulbureandreit if you check your logs, you should also see an error printout there:
`"encountered variable with one unique value"`

What seems to be happening is that this variable has only one unique value in the entire training set, e.g. 0 
Thus, the model can not learn a meaningful relationship towards the forecast. 

Please exclude this variable from configured regressors for all series where the variable has only one unique value in the train dataset. This should resolve your issue.
